export const departments = [
  { value: "Office of the City Mayor", label: "Office of the City Mayor" },
  { value: "Office of the Vice Mayor", label: "Office of the Vice Mayor" },
  { value: "Office of the City Council", label: "Office of the City Council" },
  { value: "Office of the Sangguniang Panlungsod", label: "Office of the Sangguniang Panlungsod" },
  { value: "Office of the Secretary", label: "Office of the Secretary" },
  { value: "Office of the City Treasurer (and Assistant)", label: "Office of the City Treasurer (and Assistant)" },
  { value: "Office of the City Assessor (and Assistant)", label: "Office of the City Assessor (and Assistant)" },
  { value: "Office of the City Accountant", label: "Office of the City Accountant" },
  { value: "City Budget Office / Budget Officer", label: "City Budget Office / Budget Officer" },
  { value: "Office of the City Planning & Development Coordinator (Planning & Development Office)", label: "Office of the City Planning & Development Coordinator (Planning & Development Office)" },
  { value: "City Engineer / Engineering Office", label: "City Engineer / Engineering Office" },
  { value: "City Health Office / Health Officer", label: "City Health Office / Health Officer" },
  { value: "Civil Registry Office / City Civil Registrar", label: "Civil Registry Office / City Civil Registrar" },
  { value: "City Administrator Office", label: "City Administrator Office" },
  { value: "City Legal Office / Legal Officer", label: "City Legal Office / Legal Officer" },
  { value: "City Social Welfare & Development Office", label: "City Social Welfare & Development Office" },
  { value: "City Veterinarian Office / City Veterinarian", label: "City Veterinarian Office / City Veterinarian" },
  { value: "City General Services Office / General Services Officer", label: "City General Services Office / General Services Officer" },
  { value: "City Cooperatives Office / Cooperatives Officer", label: "City Cooperatives Office / Cooperatives Officer" },
  { value: "City Building Office / Building Officer", label: "City Building Office / Building Officer" },
  { value: "Office of the City Agriculturist / Agriculture Office", label: "Office of the City Agriculturist / Agriculture Office" },
  { value: "Office of the City Architect / City Architect Office", label: "Office of the City Architect / City Architect Office" },
  { value: "Office of the City Information Officer / ICT / Information Office", label: "Office of the City Information Officer / ICT / Information Office" },
  { value: "Office of the Environment and Natural Resources Officer (or similar environmental office)", label: "Office of the Environment and Natural Resources Officer (or similar environmental office)" },
  { value: "Population Office / City Population Officer", label: "Population Office / City Population Officer" },
  { value: "City Fire Station / Fire Marshal Office", label: "City Fire Station / Fire Marshal Office" },
  { value: "City Jail / Jail Warden Office", label: "City Jail / Jail Warden Office" },
  { value: "City Schools Division (local) / Schools Division Superintendent Office", label: "City Schools Division (local) / Schools Division Superintendent Office" },
  { value: "Tayabas City Budget Office", label: "Tayabas City Budget Office" },
  { value: "Tayabas City Planning & Development Coordinator Office (Planning & Development)", label: "Tayabas City Planning & Development Coordinator Office (Planning & Development)" },
  { value: "Tayabas City Public Library Office", label: "Tayabas City Public Library Office" },
  { value: "Tayabas City Public Market Office", label: "Tayabas City Public Market Office" },
  { value: "Tayabas City Agriculture Office (Agriculture / TIFARC)", label: "Tayabas City Agriculture Office (Agriculture / TIFARC)" },
  { value: "Tayabas City Tourism Office", label: "Tayabas City Tourism Office" },
  { value: "Colegio Dela Ciudad de Tayabas", label: "Colegio Dela Ciudad de Tayabas" },
];
