export const ROLES = {
  ADMIN: "4951a033-5127-43ca-91c9-f0422bc38f1e",
  MANAGER: "2cf1bfb6-7ef3-4514-91ba-ad93f308933d",
  STAFF: "c2aea2f7-edbb-4a65-bc55-8c82ec4fc9fa",
  VIEWER: "647a085a-94f6-4237-a190-0f110da1b14a",
};

export const PERMISSIONS = {
  DASHBOARD: "dashboard",
  ITEMS_MANAGEMENT: "items_management",
  STOCK_RECEIVING: "stock_receiving",
  STOCK_ISSUANCE: "stock_issuance",
  CUSTODIANS: "custodians",
  STOCK_CARD: "stock_card",
  PHYSICAL_COUNT: "physical_count",
  DEPT_REQUESTS: "dept_requests",
  USER_ROLES: "user_roles",
  SETTINGS: "settings",
};

export const rolePermissions: Record<string, string[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.ITEMS_MANAGEMENT,
    PERMISSIONS.STOCK_RECEIVING,
    PERMISSIONS.STOCK_ISSUANCE,
    PERMISSIONS.CUSTODIANS,
    PERMISSIONS.STOCK_CARD,
    PERMISSIONS.PHYSICAL_COUNT,
    PERMISSIONS.DEPT_REQUESTS,
    PERMISSIONS.USER_ROLES,
    PERMISSIONS.SETTINGS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.ITEMS_MANAGEMENT,
    PERMISSIONS.STOCK_RECEIVING,
    PERMISSIONS.STOCK_ISSUANCE,
    PERMISSIONS.CUSTODIANS,
    PERMISSIONS.STOCK_CARD,
    PERMISSIONS.PHYSICAL_COUNT,
    PERMISSIONS.DEPT_REQUESTS,
    PERMISSIONS.SETTINGS,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.ITEMS_MANAGEMENT,
    PERMISSIONS.STOCK_RECEIVING,
    PERMISSIONS.STOCK_ISSUANCE,
    PERMISSIONS.CUSTODIANS,
    PERMISSIONS.STOCK_CARD,
    PERMISSIONS.PHYSICAL_COUNT,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.CUSTODIANS,
    PERMISSIONS.STOCK_CARD,
  ],
};

export const ROLE_UUID_MAP: Record<string, string> = {
  admin: ROLES.ADMIN,
  manager: ROLES.MANAGER,
  staff: ROLES.STAFF,
  viewer: ROLES.VIEWER,
};

export function getRoleNameFromId(roleId: string): string | undefined {
  return Object.keys(ROLES).find(key => ROLES[key as keyof typeof ROLES] === roleId)?.toLowerCase();
}
